// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activewaifu struct {
	ID          int64
	Userid      pgtype.Int8
	Waifuid     pgtype.Int8
	Createddate pgtype.Timestamp
	Updateddate pgtype.Timestamp
}

type Activity struct {
	ID            int64
	Userid        pgtype.Int8
	Activity      pgtype.Text
	Duedate       pgtype.Timestamp
	Completeddate pgtype.Timestamp
	Createddate   pgtype.Timestamp
	Updateddate   pgtype.Timestamp
}

type Favorite struct {
	ID          int64
	Userid      pgtype.Int8
	Waifuid     pgtype.Int8
	Createddate pgtype.Timestamp
	Updateddate pgtype.Timestamp
}

type User struct {
	ID          int64
	Displayname pgtype.Text
	Email       pgtype.Text
	Password    pgtype.Text
	Createddate pgtype.Timestamp
	Updateddate pgtype.Timestamp
}

type Usersetting struct {
	ID          int64
	Userid      pgtype.Int8
	Createddate pgtype.Timestamp
	Updateddate pgtype.Timestamp
}

type Waifu struct {
	ID          int64
	Name        pgtype.Text
	Hobby       pgtype.Text
	Bio         pgtype.Text
	Image       pgtype.Text
	Createddate pgtype.Timestamp
	Updateddate pgtype.Timestamp
}
