// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"navbar bg-base-100 shadow-sm bg-[#fff0f6]\"><div class=\"flex-1\"><a class=\"btn btn-ghost text-xl text-[#f472b6]\">Love My Waifu</a></div><div class=\"flex-none\"><ul class=\"menu menu-horizontal px-1\"><li class=\"text-[#f472b6] px-6\"><a href=\"/about\">About</a></li><li class=\"text-[#f472b6] px-6\"><a href=\"/login\">Log In</a></li><li class=\"text-[#f472b6] px-6\"><a href=\"/signup\">Sign Up</a></li></ul></div></div><hr class=\"bg-[#f472b6] border-0 h-px\"><div class=\"navbar bg-base-100 shadow-sm bg-[#fff0f6]\"><div class=\"flex-1\"><a class=\"btn btn-ghost text-xl text-[#f472b6]\">Love My Waifu</a></div><div class=\"flex-none\"><ul class=\"menu menu-horizontal px-1\"><li class=\"text-[#f472b6] px-6\"><a href=\"/about\">Log History</a></li><li class=\"text-[#f472b6] px-6\"><a href=\"/login\">Favorites</a></li><li><details><summary class=\"text-[#f472b6] px-6\">User XXX</summary><ul class=\"bg-base-100 bg-[#fff0f6] rounded-t-none p-2\"><li class=\"text-[#f472b6] px-6\"><a>Settings</a></li><li class=\"text-[#f472b6] px-6\"><a>Log Out</a></li></ul></details></li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
