// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActiveWaifu = `-- name: CreateActiveWaifu :one
INSERT INTO activeWaifus (
    userId, waifuId
) VALUES (
    $1, $2
) 
RETURNING id, userid, waifuid, createddate, updateddate
`

type CreateActiveWaifuParams struct {
	Userid  pgtype.Int8
	Waifuid pgtype.Int8
}

func (q *Queries) CreateActiveWaifu(ctx context.Context, arg CreateActiveWaifuParams) (Activewaifu, error) {
	row := q.db.QueryRow(ctx, createActiveWaifu, arg.Userid, arg.Waifuid)
	var i Activewaifu
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Waifuid,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const createActivities = `-- name: CreateActivities :one
INSERT INTO activities (
    userId, activity, dueDate, completedDate
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, userid, activity, duedate, completeddate, createddate, updateddate
`

type CreateActivitiesParams struct {
	Userid        pgtype.Int8
	Activity      pgtype.Text
	Duedate       pgtype.Timestamp
	Completeddate pgtype.Timestamp
}

func (q *Queries) CreateActivities(ctx context.Context, arg CreateActivitiesParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivities,
		arg.Userid,
		arg.Activity,
		arg.Duedate,
		arg.Completeddate,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Activity,
		&i.Duedate,
		&i.Completeddate,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const createFavorites = `-- name: CreateFavorites :one
INSERT INTO favorites (
    userId, waifuId
) VALUES (
    $1, $2
) 
RETURNING id, userid, waifuid, createddate, updateddate
`

type CreateFavoritesParams struct {
	Userid  pgtype.Int8
	Waifuid pgtype.Int8
}

func (q *Queries) CreateFavorites(ctx context.Context, arg CreateFavoritesParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, createFavorites, arg.Userid, arg.Waifuid)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Waifuid,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    displayName, email, password
) VALUES (
    $1, $2, $3
) 
RETURNING id, displayname, email, password, createddate, updateddate
`

type CreateUserParams struct {
	Displayname pgtype.Text
	Email       pgtype.Text
	Password    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Displayname, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Displayname,
		&i.Email,
		&i.Password,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const createWaifu = `-- name: CreateWaifu :one
INSERT INTO waifus (
    name, hobby, bio, image
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, name, hobby, bio, image, createddate, updateddate
`

type CreateWaifuParams struct {
	Name  pgtype.Text
	Hobby pgtype.Text
	Bio   pgtype.Text
	Image pgtype.Text
}

func (q *Queries) CreateWaifu(ctx context.Context, arg CreateWaifuParams) (Waifu, error) {
	row := q.db.QueryRow(ctx, createWaifu,
		arg.Name,
		arg.Hobby,
		arg.Bio,
		arg.Image,
	)
	var i Waifu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.Image,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const deleteActiveWaifus = `-- name: DeleteActiveWaifus :exec
DELETE FROM activeWaifus
WHERE id = $1
`

func (q *Queries) DeleteActiveWaifus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteActiveWaifus, id)
	return err
}

const deleteActivities = `-- name: DeleteActivities :exec
DELETE FROM activities
WHERE id = $1
`

func (q *Queries) DeleteActivities(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteActivities, id)
	return err
}

const deleteFavorites = `-- name: DeleteFavorites :exec
DELETE FROM favorites
WHERE id = $1
`

func (q *Queries) DeleteFavorites(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFavorites, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteWaifus = `-- name: DeleteWaifus :exec
DELETE FROM waifus
WHERE id = $1
`

func (q *Queries) DeleteWaifus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWaifus, id)
	return err
}

const getActiveWaifu = `-- name: GetActiveWaifu :one
SELECT id, userid, waifuid, createddate, updateddate FROM activeWaifus
WHERE userId = $1 LIMIT 1
`

func (q *Queries) GetActiveWaifu(ctx context.Context, userid pgtype.Int8) (Activewaifu, error) {
	row := q.db.QueryRow(ctx, getActiveWaifu, userid)
	var i Activewaifu
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Waifuid,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const getActivities = `-- name: GetActivities :one
SELECT id, userid, activity, duedate, completeddate, createddate, updateddate FROM activities
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetActivities(ctx context.Context, id int64) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivities, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Activity,
		&i.Duedate,
		&i.Completeddate,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const getFavorites = `-- name: GetFavorites :one
SELECT id, userid, waifuid, createddate, updateddate FROM favorites
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFavorites(ctx context.Context, id int64) (Favorite, error) {
	row := q.db.QueryRow(ctx, getFavorites, id)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Waifuid,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, displayname, email, password, createddate, updateddate FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Displayname,
		&i.Email,
		&i.Password,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const getWaifu = `-- name: GetWaifu :one
SELECT id, name, hobby, bio, image, createddate, updateddate FROM waifus
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWaifu(ctx context.Context, id int64) (Waifu, error) {
	row := q.db.QueryRow(ctx, getWaifu, id)
	var i Waifu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.Image,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const updateActiveWaifus = `-- name: UpdateActiveWaifus :one
UPDATE activeWaifus
    set userId = $2, 
    waifuId = $3
WHERE id = $1
RETURNING id, userid, waifuid, createddate, updateddate
`

type UpdateActiveWaifusParams struct {
	ID      int64
	Userid  pgtype.Int8
	Waifuid pgtype.Int8
}

func (q *Queries) UpdateActiveWaifus(ctx context.Context, arg UpdateActiveWaifusParams) (Activewaifu, error) {
	row := q.db.QueryRow(ctx, updateActiveWaifus, arg.ID, arg.Userid, arg.Waifuid)
	var i Activewaifu
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Waifuid,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const updateActivities = `-- name: UpdateActivities :one
UPDATE activities
    set userId = $2, 
    activity = $3, 
    dueDate = $4, 
    completedDate = $5
WHERE id = $1
RETURNING id, userid, activity, duedate, completeddate, createddate, updateddate
`

type UpdateActivitiesParams struct {
	ID            int64
	Userid        pgtype.Int8
	Activity      pgtype.Text
	Duedate       pgtype.Timestamp
	Completeddate pgtype.Timestamp
}

func (q *Queries) UpdateActivities(ctx context.Context, arg UpdateActivitiesParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivities,
		arg.ID,
		arg.Userid,
		arg.Activity,
		arg.Duedate,
		arg.Completeddate,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Activity,
		&i.Duedate,
		&i.Completeddate,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const updateFavorites = `-- name: UpdateFavorites :one
UPDATE favorites
    set userId = $2, 
    waifuId = $3
WHERE id = $1
RETURNING id, userid, waifuid, createddate, updateddate
`

type UpdateFavoritesParams struct {
	ID      int64
	Userid  pgtype.Int8
	Waifuid pgtype.Int8
}

func (q *Queries) UpdateFavorites(ctx context.Context, arg UpdateFavoritesParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, updateFavorites, arg.ID, arg.Userid, arg.Waifuid)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Waifuid,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
    set displayName = $2, 
    email = $3, 
    password = $4 
WHERE id = $1
RETURNING id, displayname, email, password, createddate, updateddate
`

type UpdateUserParams struct {
	ID          int64
	Displayname pgtype.Text
	Email       pgtype.Text
	Password    pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Displayname,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Displayname,
		&i.Email,
		&i.Password,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}

const updateWaifus = `-- name: UpdateWaifus :one
UPDATE waifus
    set name = $2, 
    hobby = $3, 
    bio = $4, 
    image = $5
WHERE id = $1
RETURNING id, name, hobby, bio, image, createddate, updateddate
`

type UpdateWaifusParams struct {
	ID    int64
	Name  pgtype.Text
	Hobby pgtype.Text
	Bio   pgtype.Text
	Image pgtype.Text
}

func (q *Queries) UpdateWaifus(ctx context.Context, arg UpdateWaifusParams) (Waifu, error) {
	row := q.db.QueryRow(ctx, updateWaifus,
		arg.ID,
		arg.Name,
		arg.Hobby,
		arg.Bio,
		arg.Image,
	)
	var i Waifu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.Image,
		&i.Createddate,
		&i.Updateddate,
	)
	return i, err
}
